name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Set up Android SDK
        uses: android-actions/setup-sdk@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run install_android_sdk.sh
        run: |
          chmod +x install_android_sdk.sh
          ./install_android_sdk.sh
      - name: Get tag name
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          name: LDR Gotchi ${{ steps.tag_name.outputs.TAG_NAME }}
          body: |
            ## LDR Gotchi Release ${{ steps.tag_name.outputs.TAG_NAME }}
            
            ### What's New
            - Latest stable build of LDR Gotchi
            - Compatible with Android 5.0+ (API level 21)
            
            ### Installation
            1. Download the APK file below
            2. Enable "Install from unknown sources" in your Android settings
            3. Install the APK on both partners' devices
            4. Start caring for your shared virtual pet!
            
            ### Features
            - Pet evolution system (egg → baby → child → adult)
            - Memory matching game
            - Achievement system
            - Partner messaging
            - Cross-device data sharing
          files: |
            build/app/outputs/flutter-apk/app-release.apk 