name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Get tag name
      id: tag_name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
        release_name: LDR Gotchi ${{ steps.tag_name.outputs.TAG_NAME }}
        draft: false
        prerelease: false
        body: |
          ## LDR Gotchi Release ${{ steps.tag_name.outputs.TAG_NAME }}
          
          ### What's New
          - Latest stable build of LDR Gotchi
          - Compatible with Android 5.0+ (API level 21)
          
          ### Installation
          1. Download the APK file below
          2. Enable "Install from unknown sources" in your Android settings
          3. Install the APK on both partners' devices
          4. Start caring for your shared virtual pet!
          
          ### Features
          - Pet evolution system (egg → baby → child → adult)
          - Memory matching game
          - Achievement system
          - Partner messaging
          - Cross-device data sharing
    
    - name: Upload APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/flutter-apk/app-release.apk
        asset_name: ldr-gotchi-${{ steps.tag_name.outputs.TAG_NAME }}.apk
        asset_content_type: application/vnd.android.package-archive 